attendance/urls.py
from django.conf.urls import url
from . import views

app_name = 'attendance'
urlpatterns = [
    url(r'^student_profile/(?P<slug>.*)/$', views.student_profile, name="student_profile"),
    url(r'^add_attendance/$', views.add_attendance, name="add_attendance"),
    url(r'^today_attendance/$', views.today_attendance, name="today_attendance"),
    url(r'^view_attendance/$', views.view_attendance, name="view_attendance"),
    url(r'^day_attendance/(?P<attendance_date>.*)/$', views.day_attendance, name="day_attendance"),
    url(r'^view_messages/$', views.view_messages, name="view_messages"),
    url(r'^new_message/$', views.new_faculty_message, name="new_faculty_message"),
    url(r'^recieved_messages/$', views.recieved_messages, name="recieved_messages"),
    # url(r'^login_check/$', views.login_check, name="login_check"),
]

attendance_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^', include('attendance.urls')),
    url(r'^admin/', admin.site.urls),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^student_login/$', views.student_login, name="student_login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^dashboard/$', views.dashboard_faculty, name="dashboard"),
    # url(r'^dashboard/$', views.dashboard_student, name="dashboard_student"),
    url(r'^add_student/$', views.add_student, name="add_student"),
    # url(r'^login_check/$', views.login_check, name="login_check"),
]

home/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime
# Create your models here.

class Sections(models.Model):
    name = models.CharField(max_length = 200, unique=True)
    creation_date = models.DateTimeField('date published', default=datetime.now)

    def __str__(self):
        return self.name

class Facultys(models.Model):
    name = models.CharField(max_length = 200)
    email = models.EmailField(max_length = 100, unique=True)
    password = models.CharField(max_length = 200)
    section = models.ForeignKey(Sections, on_delete=models.CASCADE, default=0)
    creation_date = models.DateTimeField('date published', default=datetime.now)

    def __str__(self):
        # dat = self.name + self.email + self.section +" " +self.section
        return self.name +" " +self.email

class Students(models.Model):
    name = models.CharField(max_length=200)
    roll_no = models.CharField(max_length=200)
    email = models.EmailField(max_length = 100)
    phone = models.IntegerField(default = 1)
    mother_name = models.CharField(max_length=201)
    gender = models.IntegerField()
    section = models.ForeignKey(Sections, on_delete=models.CASCADE, default=0)
    slug = models.SlugField(max_length=251, default="1")
    creation_date = models.DateTimeField('date published', default=datetime.now)

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)

        super(Students, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from .models import *
from django.contrib import messages
from django.views import generic
import datetime
from django.core.serializers.json import DjangoJSONEncoder
# Create your views here.

def index(request):
    if request.method == 'POST':
        try:
            faculty_data = Facultys.objects.get(email = request.POST['email'])
            if faculty_data:
                if faculty_data.password == request.POST['password']:
                    request.session['faculty'] = faculty_data.pk
                    content = {
                        'data': faculty_data
                    }
                    # messages.add_message(request, messages.INFO, 'Logged in Successfully')
                    messages.success(request, 'Logged in Successfully')
                    response = HttpResponseRedirect(reverse('home:dashboard'))
                    response.set_cookie('name', "Dishant")
                    return response
                    # return HttpResponseRedirect('/dashboard', content)
        # render(request, 'home/faculty_dashboard.html', content)
                else:
                    content = {
                    'data': faculty_data
                    }
                    # messages.add_message(request, messages.ERROR, 'No match Wrong Password.')
                    messages.error(request, 'Sorry, either of your provided information is wrong.')
                    return render(request, 'home/home.html', content)
        except ObjectDoesNotExist:
            return render(request, 'home/home.html')
    else:
        return render(request, 'home/home.html')

def student_login(request):
    if request.method == 'POST':
        try:
            studnt_data = Students.objects.get(roll_no = request.POST['univ_rlno'])
            if studnt_data:
                if studnt_data.name == request.POST['name']:
                    request.session['student'] = studnt_data.pk
                    # content = {
                    #     'data': faculty_data
                    # }
                    messages.success(request, 'Logged in Successfully')
                    return HttpResponseRedirect(reverse('home:dashboard'))
        # render(request, 'home/faculty_dashboard.html', content)
                else:
                    messages.error(request, 'Sorry, either of your provided information is wrong.')
                    return HttpResponseRedirect(reverse('home:index'))
                    # return render(request, 'home/login.html', content)
        except ObjectDoesNotExist:
            messages.error(request, 'User does not exist.')
            return HttpResponseRedirect(reverse('home:index'))
    else:
        return render(request, 'home/login.html')

def dashboard_faculty(request):
    if 'faculty' in request.session:
        sessn_val = request.session['faculty']
        faculty_data = Facultys.objects.get(pk=sessn_val)
        sectn_data = Sections.objects.get(name=faculty_data.section)
        content = {'data': faculty_data, 'sectn_data': sectn_data}
        return render(request, 'home/view_students.html', content)
    elif 'student' in request.session:
        sessn_val = request.session['student']
        student_data = Students.objects.get(pk=sessn_val)
        sectn_data = Sections.objects.get(name=student_data.section)
        content = {'data': student_data, 'sectn_data': sectn_data}
        return render(request, 'home/student_info.html', content)
    else:
        messages.error(request, 'Sorry, Login First!!!')
        return render(request, 'home/home.html') 
        # return HttpResponse(sectn_data)

def add_student(request):
    content={}
    if request.method == 'POST':
        faculty_data = Facultys.objects.get(pk=request.POST['id_faculty'])
        sectn_data = Sections.objects.get(name=faculty_data.section)
        stdnt = sectn_data.students_set.create(name=request.POST['name'], email=request.POST['email'], phone=request.POST['phone_no'], gender=request.POST['gender'], mother_name=request.POST['mother_name'])
        chek = stdnt.save()
        today = datetime.datetime.now()
        get_lastid = Students.objects.latest('id')
        set_roll_no = sectn_data.name + str(today.year) + str(get_lastid.id)
        student_data = Students.objects.get(id=get_lastid.id)
        student_data.roll_no = set_roll_no
        check1 = student_data.save()
        if get_lastid:
            messages.success(request, "Student Added Successfully")
        else:
            messages.error(request, "Error in adding student")
    # return HttpResponseRedirect('/dashboard', content)
    return HttpResponseRedirect(reverse('home:dashboard'))

def logout(request):
    try:
        if 'faculty' in request.session:
            del request.session['faculty']
        elif 'student' in request.session:
            del request.session['student']
        # return HttpResponseRedirect(reverse('home:index', {
        #     'error_note': 'Logged out Successfully'
        # }))
        auth.logout(request)
        messages.success(request, "Logged Out Successfully")
        return HttpResponseRedirect(reverse('home:index'))

    except:
        messages.error(request, "Error in logging Out")
        return HttpResponseRedirect(reverse('home:index'))

home/templates/home/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" > -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
  <body>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <p><img src="{% static 'home/images/att.jpg' %}" width="90px" ></p>
                </div>
                <div class="col-md-8">
                  <!---  {% if 'faculty' in request.session %}
                    {{ request.session.faculty }}
                    {{ data.name }}
                    <a href="{% url 'home:logout' %}">Logout</a>
                    {% else %}
                    <a href="{% url 'home:index' %}">Login</a>
                    {% endif %} ---->
                </div>
            </div>
        </div>

        <nav class="navbar cus_navbar">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
             <!--  {% if 'faculty' in request.session %}
              <a class="navbar-brand" href="{% url 'home:dashboard' %}">Dashboard</a>
              {% endif %} -->
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Faculties <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Page 1-1</a></li>
                    <li><a href="#">Page 1-2</a></li>
                    <li><a href="#">Page 1-3</a></li>
                  </ul>
                </li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact us</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">                
                {% if 'faculty' in request.session %}
                <!-- <li>{{ request.session.faculty }}</li> -->
                <!-- <li>{{ data.name }}</li> -->
                <li><a href="{% url 'home:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                {% elif 'student' in request.session %}
                <li><a href="{% url 'home:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                {% endif %}
                <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> -->
              </ul>
            </div>
          </div>
        </nav>
    </header>
    {% if 'name' in request.COOKIES %}
    {{ request.cookies.name }}
    {% endif %}
    <section class="middl_sectn">
      <div class="container">

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <!-- <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li> -->
            <div {% if message.tags %} class="alert {% if message.tags == 'error' %} {{'alert-danger' }} {% else %} alert-{{ message.tags }} {% endif %} alert-dismissable fade in" {% endif %}>
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        
        {% block content %}

        {% endblock %}
      </div>
    </section>

   <!-- Footer -->
<footer class="page-footer font-small indigo">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Very long link 1</a>
          </li>
          <li>
            <a href="#!">Very long link 2</a>
          </li>
          <li>
            <a href="#!">Very long link 3</a>
          </li>
          <li>
            <a href="#!">Very long link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script> -->
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'home/js/custom_js.js' %}"></script>
    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'editor1' );
    </script>
  </body>
</html>

home/templates/home/home.html
{%  extends "home/header.html" %}

{% block content %}

<div class="text-center">
	<h2>Welcome to Attendance Management System</h2>
	{% if 'faculty' in request.session %}
	<h3><a class=" btn btn-warning" href="{% url 'home:dashboard' %}">Dashboard</a></h3>
	{% elif 'student' in request.session  %}
	<h3><a class=" btn btn-warning" href="{% url 'home:dashboard' %}">Dashboard</a></h3>
	{% else %}
	<p>Click on login to begin</p>
	<p class="login_btns"><span class="studnt_login btn btn-danger" data-toggle="modal" data-target="#student_login_modl">I am a student</span><span class="faculty_login btn btn-warning" data-toggle="modal" data-target="#faculty_login">I am a faculty</span></p>
	{% endif %}
</div>

<!--FACULTY LOGIN Modal -->
<div id="faculty_login" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Faculty Login</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'home:index' %}">
    		{% csrf_token %}
		  <div class="form-group">
		    <label for="email">Email address:</label>
		    <input type="email" name="email" class="form-control">
		  </div>
		  <div class="form-group">
		    <label for="pwd">Password:</label>
		    <input type="password" class="form-control" name="password">
		  </div>
		  <div class="checkbox">
		    <label><input type="checkbox"> Remember me</label>
		  </div>
		  <button type="submit" name="submit" class="btn btn-success">Login</button>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<!--STUDENT LOGIN Modal -->
<div id="student_login_modl" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Faculty Login</h4>
      </div>
      <div class="modal-body">
        <form method="post" id="stdnt_logn_form" action="{% url 'home:student_login' %}">
    		{% csrf_token %}
			<p id="stdnt_logn_form_error"></p>
		  <div class="form-group">
		    <label for="email">Name:</label>
		    <input type="text" id="stdnt_logn_name" name="name" class="form-control">
		  </div>
		  <div class="form-group">
		    <label for="pwd">University Roll No:</label>
		    <input type="text" id="stdnt_logn_rollno" class="form-control" name="univ_rlno">
		  </div>
		  <div class="checkbox">
		    <label><input type="checkbox"> Remember me</label>
		  </div>
		  <button type="submit" name="submit" class="btn btn-success">Login</button>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

{% endblock %}

home/templates/home/main_dashboard.html
{%  extends "home/header.html" %}

{% block content %}


	<!-- <div class="row">
		<div class="col-md-12">
			<p>Faculty Dashboard</p>

			<p>Name: {{ data.name }}</p>
			<p>Section: </p>
		</div>
	</div> -->
	<div class="row">
		{% if check_msg %} <p>{{ check_msg }}</p>{% endif %}
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="faculty_dash_sidebr">		
				<div class="dash_user">
					<p>{{ data.name }}</p>
					<p>{{ data.section }}</p>
				</div>	
				{% if 'faculty' in request.session %}	
				<p class="sidebr_elemnt"><a href="{% url 'home:dashboard' %}">View Students</a></p>
				<p class="sidebr_elemnt sidebr_elemnt_hdng">Attendance</p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:add_attendance' %}">Today's Attendance</a></p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:view_attendance' %}">View Attendance</a></p>
				<p class="sidebr_elemnt sidebr_elemnt_hdng">View Messages</p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:new_faculty_message' %}">New Message</a></p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:view_messages' %}">Send Messages</a></p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:recieved_messages' %}">Recieved Messages</a></p>
				{% elif 'student' in request.session %}
				<p class="sidebr_elemnt"><a href="{% url 'home:dashboard' %}">View Details</a></p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:view_attendance' %}">View Attendance</a></p>
				<p class="sidebr_elemnt"><a href="{% url 'attendance:view_messages' %}">View Messages</a></p>
				{% endif %}
			</div>
		</div>
		<div class="col-md-9">
			<div class="faculty_dash_ryt">
				{% block dashboard %}

				{% endblock %}
			</div>
		</div>
	</div>




{% endblock %}

home/templates/home/student_info.html
{%  extends "home/main_dashboard.html" %}

{% block dashboard %}

<div class="studnt_dash_info">    
    <table class="table">
        <tr>
            <th>University Roll No.</th>
            <td>{{ data.roll_no }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{% if data.gender == 1 %} {{ 'Male' }} {% else %} {{ 'Female' }}{% endif %}</td>
        </tr>
        <tr>
            <th>Mother's Name</th>
            <td>{{ data.mother_name }}</td>
        </tr>
        <tr>
            <th>Phone Number</th>
            <td>{{ data.phone }}</td>
        </tr>
        <tr>
            <th>E-mail</th>
            <td>{{ data.email }}</td>
        </tr>
    </table>
</div>

<!-- <p class="add_stdnt"><a href="javascript:void(0)" class="add_new_student btn btn-default">Add Student</a></p>

<form method="post" class="add_new_student_frm disp-none" action="{% url 'home:add_student' %}">
    {% csrf_token %}
    <div class="row">
    	<div class="col-md-6">
    		<input type="hidden" name="id_faculty" value="{{ request.session.faculty }}">
    		Name: <input type="text" name="name" class="form-control" required > 
    	</div>
    	<div class="col-md-6">
    		Univ Roll No.: <input type="text" name="roll_no" value="{% now 'Y' %}{{ data.section }}" class="form-control" readonly="" >
    	</div>
    	<div class="col-md-6">
    		Phone No. : <input type="text" name="phone_no" class="form-control" required > 
    	</div>
    	<div class="col-md-6">
    		Email: <input type="email" name="email" class="form-control" required > 
    	</div>
    	<div class="col-md-6">
    		Mother's Name: <input type="text" name="mother_name" class="form-control" > 
    	</div>
    	<div class="col-md-6">
    		<label>Gender: <input type="radio" name="gender" value="1" > Male &nbsp;
    		<input type="radio" name="gender" value="2" > Female </label>
    	</div>
    	<div class="col-md-12">
    		<input type="submit" name="submit" value="Add Student" class="btn form-control btn-success" >
    	</div>
    </div>   
    
    <!-- Roll No: <input type="text" name="rollno" value="112{% now 'Y' %}" readonly=""> <br> -->    
    
<!-- </form> -->


<!-- {% with i=1 %} -->

<!-- <table class="table"> -->
<!-- 	<thead>
		<tr>
			<th>S No.</th>
			<th>Name</th>
			<th>Univ Roll No.</th>
			<th>Phone No.</th>
			<th>E-mail</th>							
		</tr>
	</thead>
	<tbody>
		{% for students in sectn_data.students_set.all %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ students.name }}</td>
			<td>{{ students.roll_no }}</td>
			<td>{{ students.gender }}</td>
			<td>{{ students.email }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table> -->
<!-- {% endwith %} -->
{% endblock %}

home/templates/home/view_attendance.html
{%  extends "home/main_dashboard.html" %}

{% block dashboard %}
{% load custom_tags %}
<table class="table table-stripped table-bordered">
{% if  'faculty' in request.session %}
	<thead>
		<tr>
			<th>S No.</th>
			<th>Student Name</th>
			<th>Total attendance</th>
		</tr>
	</thead>
	<tbody>
		{% for attendance in attendance_data  %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td><a href="{% url 'attendance:day_attendance' attendance.attendance_date %}">{{ attendance.attendance_date }}</a></td>  <!-- attendance.attendance_date -->
			<!--{% for student in section_data.students_set.all %}-->
			<!--<td>{{ student.name }}</td>-->
            <!--{% with attendance.student|split:"," as attndnc %}-->
            <!--{% with student.pk|int_to_str as studnt_id %}-->
            <!--<td>{{ attndnc }}</td>-->
			<!--{% if studnt_id in attndnc %}-->
			<!--<td>{{ ' Present ' }}</td>-->
			<!--{% else %}-->
			<!--<td>{{ ' Absent ' }}</td>-->
			<!--{% endif %}-->
            <!--{% endwith %}-->
            <!--{% endwith %}-->
			<!--{% endfor %}-->
			<td>total</td>
		</tr>
		{% endfor %}
	</tbody>
{% endif %}
	
</table>
{% endblock %}

home/templates/home/view_students.html
{%  extends "home/main_dashboard.html" %}

{% block dashboard %}

<p class="add_stdnt"><a href="javascript:void(0)" class="add_new_student btn btn-default">Add Student</a></p>

<form method="post" class="add_new_student_frm disp-none" action="{% url 'home:add_student' %}">
    {% csrf_token %}
    <div class="row">
    	<div class="col-md-6">
    		<input type="hidden" name="id_faculty" value="{{ request.session.faculty }}">
    		Name: <input type="text" name="name" class="form-control" required > 
    	</div>
    	<div class="col-md-6">
    		Univ Roll No.: <input type="text" name="roll_no" value="{% now 'Y' %}{{ data.section }}" class="form-control" readonly="" >
    	</div>
    	<div class="col-md-6">
    		Phone No. : <input type="text" name="phone_no" class="form-control" required > 
    	</div>
    	<div class="col-md-6">
    		Email: <input type="email" name="email" class="form-control" required > 
    	</div>
    	<div class="col-md-6">
    		Mother's Name: <input type="text" name="mother_name" class="form-control" > 
    	</div>
    	<div class="col-md-6">
    		<label>Gender: <input type="radio" name="gender" value="1" > Male &nbsp;
    		<input type="radio" name="gender" value="2" > Female </label>
    	</div>
    	<div class="col-md-12">
    		<input type="submit" name="submit" value="Add Student" class="btn form-control btn-success" >
    	</div>
    </div>   
    
    <!-- Roll No: <input type="text" name="rollno" value="112{% now 'Y' %}" readonly=""> <br> -->    
    
</form>


<!-- {% with i=1 %} -->

<table class="table">
	<thead>
		<tr>
			<th>S No.</th>
			<!--<th>View</th>-->
			<th>Name</th>
			<th>Univ Roll No.</th>
			<th>Phone No.</th>
			<th>E-mail</th>							
		</tr>
	</thead>
	<tbody>
		{% for students in sectn_data.students_set.all %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<!--<td><a target="_blank" href="{% url 'attendance:student_profile' students.slug %}"><small><i class="fa fa-eye" aria-hidden="true"></i></small></a></td>-->
			<td class="studnt_nme"><a target="_blank" href="{% url 'attendance:student_profile' students.slug %}"><small><i class="fa fa-eye" aria-hidden="true"></i> View Profile</small><span>{{ students.name }}</span></a></td>
			<td>{{ students.roll_no }}</td>
			<td>{{ students.phone }}</td>
			<td>{{ students.email }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<!-- {% endwith %} -->
{% endblock %}